# /etc/dnsmasq.d/10-forwarding.conf
# Author: mrjcsh386@gmail.com
# 5 February, 2026


# Upstream DNS servers
domain-needed
strict-order

# Local SoA DNS server
#server=/corp.example/192.168.10.53
# Cloud flare DNS server
server=1.1.1.1
