# /etc/dnsmasq.d/20-cache.conf
# Author: mrjcsh386@gmail.com
# 5 February, 2026


# DNS cache configuration
cache-size=150

# Query logging is useful during initial deployment and may be disabled
# later to reduce log volume. Uncomment to enable logging queries.
#log-queries
