# /etc/dnsmasq.conf/30-dhcp.conf
# Author: mrjcsh386@gmail.com
# 5 February, 2026


# DHCP Configuration
# Uncomment/define the following directives to enable DHCP
#dhcp-autoritative

# If you have more than one network, you will need to repeat this for each
# network on which you want to supply DHCP service.
#dhcp-range=192.168.0.50,192.168.0.150,12h
#dhcp-range=172.16.0.10,172.16.200.254,24h

# Setting this option allows dnsmasq to answer queries as an FQDN. To have a
# host named widgets, and the following option configured as contoso.example,
# dnsmasq will reply to any queries for that host in response to
# widgets.contoso.example.
#domain=contoso.example

# Log DHCP assignments. Useful for initial deployment. Disable to reduce log
# expansion if that is a priority.
#log-dhcp

# Defined dhcp hosts file for static assignments
#dhcp-hostsfile=/etc/dnsmasq.d/dhcp.hosts
